CC = gcc
CFLAGS = -Wall -Wextra -pedantic -g

all: HungryVeryMuch PideShop

HungryVeryMuch: HungryVeryMuch.c
	$(CC) $(CFLAGS) -o HungryVeryMuch HungryVeryMuch.c

PideShop: PideShop.c
	$(CC) $(CFLAGS) -o PideShop PideShop.c

clean:
	rm -f HungryVeryMuch PideShop